### ISSUE TITLE
CI/brigade.js: create publish/release event(s)

### ISSUE THREAD

**Issue by vdice** [Azure/brigade-charts#2]
The initial `brigade.js` just introduced `test` runs for PRs.

We may want:
 - a publish event handler to watch for pushes to master and run `make build index` and merge the corresponding git commit to update the chart artifacts/index.yaml (and thereby update the helm repository) (or perhaps we just instruct contributors to do so as part of PR?)
 - a release event handler to watch for tag pushes, if we plan on tagging all charts together (perhaps not?)

**Comment by rmb938** [comment]
Could we move the chart repo to a bucket or something? This way the brigade github token doesn't need access to push to the repo and we don't make the commits on master gross with packaging and index updates.

**Comment by rmb938** [comment]
Or move it to a gh-pages branch instead of a docs folder?

**Comment by vdice** [comment]
Closing in favor of https://github.com/Azure/brigade-charts/issues/28 -- following the approach kindly suggested in https://github.com/Azure/brigade-charts/issues/2#issuecomment-449446075
