### ISSUE TITLE
Missing brigade-project with appVersion v0.20.0 in chart repo

### ISSUE THREAD

**Issue by thomschke** [Azure/brigade-charts#20]
Latest versions in [brigade charts](https://azure.github.io/brigade-charts/index.yaml) are:
- `brigade` 0.20.0 -> v.0.20
- `brigade-project` 0.19.3 -> v0.19.0

So i'm missing a new version of `brigade-project` for appVersion v0.20.0.

**Comment by thomschke** [comment]
... and there is already a hint in the [docu](https://github.com/Azure/brigade/blob/v0.20.0/docs/topics/projects.md#the-brigade-project-chart-brigade--015)

**Comment by vdice** [comment]
@thomschke right you are!  Apologies for the error and thank you for filing this issue.

Fix in https://github.com/Azure/brigade-charts/pull/21
and docs amendment in https://github.com/Azure/brigade/pull/793
