### ISSUE TITLE
Use chart-testing to test prs

### ISSUE THREAD

**Issue by rmb938** [Azure/brigade-charts#8]
Use https://github.com/helm/chart-testing to test prs and updates to charts.

This is a very simple tool that can automatically test charts when they are updated via a pr.

This includes checking for valid authors, requiring version bumps for all changes (like the official helm repo) and linting the charts.

**Comment by rmb938** [comment]
How to use:

`test/ci.yaml`
```
remote: origin
target-branch: master
chart-dirs:
  - charts
excluded-charts: []
chart-repos: []
helm-extra-args: --timeout 600
```

Commands to run:

```
ct version
ct lint --config test/ct.yaml
```

For output see any pr in the official helm repo i.e for this pr https://github.com/helm/charts/pull/10151 the output is https://circleci.com/gh/helm/charts/45660?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vdice** [comment]
Migrated to https://github.com/brigadecore/charts/issues/3 ; closing.
