### ISSUE TITLE
CI steps for packaging charts and generating index.yaml

### ISSUE THREAD

**Issue by rmb938** [Azure/brigade-charts#9]
I took a quick look at the brigade.js and did not see any steps for it to package up the charts, creating the index.yaml and pushing the updates to the repo. We probably should automate that to prevent any manual issues.

**Comment by vdice** [comment]
@rmb938 good call!  We'd created https://github.com/Azure/brigade-charts/issues/2 ; let's consolidate into one ticket.

**Comment by rmb938** [comment]
ah my fault, did not see that issue. Will close this one
